version: "3.8"

services:
  spire-server:
    image: ghcr.io/spiffe/spire-server:1.14.1
    container_name: spire-server
    hostname: spire-server
    user: "0"
    volumes:
      - ./spire/server:/opt/spire/conf/server
      - ./data/server:/opt/spire/data/server
    command: ["-config", "/opt/spire/conf/server/server.conf"]
    ports:
      - "8081:8081"
    networks:
      - spire-net

  spire-agent:
    image: ghcr.io/spiffe/spire-agent:1.14.1
    container_name: spire-agent
    hostname: spire-agent
    user: "0"
    depends_on:
      - spire-server
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
      - ./data/agent:/opt/spire/data/agent
      - ./data/sockets:/opt/spire/sockets
    command: ["-config", "/opt/spire/conf/agent/agent.conf"]
    networks:
      - spire-net

  workload:
    build: ./workload
    container_name: workload-app
    depends_on:
      - spire-agent
    pid: "service:spire-agent"
    volumes:
      - ./data/sockets:/opt/spire/sockets
    environment:
      - VAULT_ADDR=${HCP_VAULT_ADDR}
      - VAULT_NAMESPACE=${HCP_VAULT_NAMESPACE}
      - SPIFFE_ENDPOINT_SOCKET=unix:///opt/spire/sockets/agent.sock
    networks:
      - spire-net

networks:
  spire-net:
    driver: bridge

